### ISSUE TITLE
Platform GUI stuck at "Fatal Error While Updating"

### ISSUE THREAD

**Issue by tian2992** [Nexedi/dream#5]
When running the GUI platform I get a cycle of alerts with "Fatal Error While Updating" and a lot of continous reloads.

Disabling the alert allows for a small while to access the new document interface.

**Comment by jerome-nexedi** [comment]
This GUI uses an HTML5 manifest and if there is an error while updating the manifest, there is this alert popup.
https://github.com/Nexedi/dream/blob/master/dream/platform/src/dream/index.js#L35 (don't forget to have grunt running if you make changes to this file)

Do you have error message in the browser console ?

**Comment by jerome-nexedi** [comment]
We are not really using github for issues / merge requests, this github is just a mirror. If you like to discuss further, I would suggest you file issue on https://lab.nexedi.com/nexedi/dream/

We are disabling issues on github now, thanks.
