### ISSUE TITLE
Re-running a stochastic simulation creates identical output.

### ISSUE THREAD

**Issue by numericOverflow** [Nexedi/dream#6]
I'd expect a model that utilizes stochastic distributions instead of fixed to produce different results when I re-run the same script, however, I'm seeing the EXACT same values across muliple runs of the model.  Either I'm not understanding something, or I need to buy a lottery ticket.  

The model I'm running is directly from the examples:
        dream\simulation\Examples\TwoServersStochastic.py

Can someone clarify for me?  In the below output, I increased the simulation time to be 10 days

```
c:\Python27\src>python manpyTest3.py
Simulation started at:  2016-01-20 18:37:36
Simulation finished at:  2016-01-20 18:38:45
The exit of each replication is:
[7299, 7280, 7285, 7296, 7283, 7303, 7286, 7255, 7301, 7295]
the 95% confidence interval for the throughput is:
lower bound: 7278.13258845
mean: 7288.3
upper bound: 7298.46741155

c:\Python27\src>python manpyTest3.py
Simulation started at:  2016-01-20 18:39:29
Simulation finished at:  2016-01-20 18:40:37
The exit of each replication is:
[7299, 7280, 7285, 7296, 7283, 7303, 7286, 7255, 7301, 7295]
the 95% confidence interval for the throughput is:
lower bound: 7278.13258845
mean: 7288.3
upper bound: 7298.46741155
```

**Comment by jerome-nexedi** [comment]
In the call to `runSimulation` we have explicitly used a seed, I guess to make create repeatable pseudo random scenarios
https://github.com/Nexedi/dream/blob/master/dream/simulation/Examples/TwoServersStochastic.py#L29

Using `seed=None` in your manpyTest3.py should be truely random.

Note that we are not really using github for issues / merge requests, this github is just a mirror. If you like to discuss further, I would suggest you file issue on https://lab.nexedi.com/nexedi/dream/
